My portfolio
telanet/Portfolio-microverse pull request #2
Opened 2022-01-13 15:13 UTC by telanet

Setting up a repository to use linters. Build first 3 sections of the mobile website using template chosen.

2022-01-13 16:30 UTC, Cathella requested changes
## 🟨 Status: Changes Requested 🛑 

### Hi @telanet 👋🏻, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## The Good points 👏🏻

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ The sections use the font and colors defined for the template

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 16:30 UTC, Cathella commented on index.html
> +    </header>
Hi @telanet  , I can see you are doing a great job on this project 😺.

However for the toolbar, I think you still have a few changes to make 🤔

- [ ] Since you are converting a figma design, as developers the conversion we make should almost come as close as possible to the figma design being referred to. I therefore, think it would be nice if adjusted the paddings of elements to match the figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4247740/149365727-a3749823-585a-45e6-9190-ce19a7e056ae.png) | ![image](https://user-images.githubusercontent.com/4247740/149366243-e58ffa77-96b9-4975-8a01-c4a231760812.png) |


- [ ] The logo is also meant to be a link (a tag). This is because is usually clicked on by users to revert back to the homepage. So it would really be nice if it was clickable 😄.
- [ ]  The hamburger button has a `<nav>` tag and I think it would be nice if we followed this structure 👇🏻
```
<header>
  <a href=""> -- logo goes here -- </a>
  <nav>
    <button> -- menu bars go here -- </button>
  </nav>
</header>
```
❓ What do you think about this structure?

2022-01-13 16:30 UTC, Cathella commented on index.html
> +            I’m Ngetich</div>
- [ ] Can you please make this an `<h1>` tag? This is because it is important semantically, and it also makes our code readable to other people and developers.

2022-01-13 16:30 UTC, Cathella commented on index.html
> +        <div class="supporting-text">I’am a Software Developer</div>
- [ ] This could also be made an `<h3>` or `<h2>` instead for semantic reasons.

2022-01-13 16:30 UTC, Cathella commented on index.html
> +        <div class="description">I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded,
- [ ] Let's make this a `<p>` tag for semantic reasons too.

2022-01-13 16:30 UTC, Cathella commented on index.html
> +                    <li><img src="images/Vector-4.png" alt="" /></li>
- [ ] I believe the images / icons in the `<li>` tag are meant to be wrapped in an `<a>` this is because they will be links to our different social accounts.
- [ ] I also think it would be nice if you fixed the linkedin icon - image to appear as it is in the figma design. I think you exported an incomplete icon as seen below 👇🏻 

![image](https://user-images.githubusercontent.com/4247740/149369218-c2c9beed-9954-477e-a220-19048ea3abae.png)

2022-01-13 19:46 UTC, micheaol requested changes
Hi @telanet , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 19:46 UTC, micheaol commented on index.html
> +            </section>
Please ensure you adjust the paddings of elements to match the Figma design as requested by the previous reviewer.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4247740/149365727-a3749823-585a-45e6-9190-ce19a7e056ae.png) | ![image](https://user-images.githubusercontent.com/4247740/149366243-e58ffa77-96b9-4975-8a01-c4a231760812.png) |

2022-01-13 19:46 UTC, micheaol commented on index.html
> +    </section>
Please ensure to make adjustments to the icons to match the design in Figma as requested by the previous reviewer.

> * [ ]  I also think it would be nice if you fixed the linkedin icon - image to appear as it is in the Figma design. I think you exported an incomplete icon as seen below 👇🏻
> 
> ![image](https://user-images.githubusercontent.com/4247740/149369218-c2c9beed-9954-477e-a220-19048ea3abae.png)

2022-01-13 21:02 UTC, Deepakdanger approved these changes
Hi @telanet, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Before merging, I Recommend working on the minor things before.
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 21:02 UTC, Deepakdanger commented on index.html
> +    </section>
- [ ] In the LinkedIn icon, the letter 'I' size should match with another icon, Kindly fix this.
- Your design 
![icon](https://user-images.githubusercontent.com/26767383/149408461-204e1a58-ff99-4bd2-b775-c58ac1af354b.PNG)

2022-01-13 21:02 UTC, Deepakdanger commented on index.html
> +            </section>
- [ ] Let's fix the navbar width to be 100% of the screen in mobile view.
- Your website
![deal1_LI](https://user-images.githubusercontent.com/26767383/149408532-9e6b241d-2483-4451-81f8-9e955948d930.jpg)

2022-01-14 02:13 UTC, merged

2022-01-18 07:39 UTC, mstanley-me reviewed
Hey @telanet , I am Stanley your reviewer for this PR 😸

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight

✔️ The repo looks professional
✔️ You did a good job pointing bugs 🐛 🐞

Required Changes ♻️

See the inline comments below for more required changes 😃

Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N.A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2022-01-18 07:39 UTC, mstanley-me commented on index.html
> +            </section>
Kindly try to make your code more organized and structured code. They will make your project look professional 😁