Recent works
telanet/Portfolio-microverse pull request #3
Opened 2022-01-15 19:45 UTC by telanet

Building the middle section of the mobile website. This sections of the mobile website include:

"Works" section
 "About myself" section

2022-01-15 20:19 UTC, Deepakdanger requested changes
Hi @telanet & @Blantraders, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [ ] The Readme should be well organized, please include all contributors & necessary details there.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-15 20:19 UTC, Deepakdanger commented on index.html
> +<div class="about" id="about-section">
- [ ] The `About me ` container should be a `section`, Kindly fix that. 🔧
 
- [ ] [OPTIONAL] 
- I recommend using `div` instead of using `section` inside any `section` tag. You have used too many `section` tags.

2022-01-15 20:51 UTC, Deepakdanger approved these changes
Hi @telanet & @Blantraders, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-15 20:53 UTC, merged

2022-01-18 07:32 UTC, mstanley-me reviewed
Hey @telanet , I am stanley your reviewer for this PR 😸

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight

✔️ The repo looks professional
✔️ You did a good job pointing bugs 🐛 🐞

Required Changes ♻️

See the inline comments below for more required changes 😃

Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N.A

Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.