Desktop portfolio
telanet/Portfolio-microverse pull request #6
Opened 2022-01-21 14:49 UTC by telanet

Create desktop version of Portfolio.

2022-01-21 15:59 UTC, moise10r requested changes
### Hi **@telanet,**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️ 
- GitHubFlow was correctly used.  ✔️   
- Good commit history ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
- [ ]  Your README looks great but you can improve it by making it more professional. A professional README file should have a project title, description, and instructions to set the project up locally. please refer to this [template](https://github.com/microverseinc/readme-template)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-21 15:59 UTC, moise10r commented on README.md
> +!(./app_screenshot.png)
- [ ] Kindly add a screenshot of your project to the README.md file to make it more professional

2022-01-21 15:59 UTC, moise10r commented on style.css
> +  align-items: center;
- [ OPTIONAL] This is great using flexbox to layout your content, congrats 👏 , But we can still improve this code by using DRY (don't repeat yourself) but why? well, I realized that you have used the property `display: flex` at multiple places, please let's keep the code clean by extracting the property into a separate class that can be reused at multiple places, see the example below: 

- CSS file
```
.d-flex {
  display: flex;
}

.flex-center {
  flex-direction: column;
  justify-content: center;
}
```
- HTML file
```
<div class="d-flex flex-center">{your content}</div>
```

And remember you can do this for all the other properties that seem to be repeated multiple times, With this, I promise you'll be coding like a pro 😉

2022-01-21 15:59 UTC, moise10r commented on index.html
>        </nav>
- [ ] Be careful with blank lines and indentation do not add blank lines, spaces, or indentations without a reason. Add two spaces of indentation to make your code more readable check the [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-01-21 15:59 UTC, moise10r commented on index.html
>          </ul>
- [ ] Please change the social-media-icons color and make position them to the center and not to the left, you must replicate the design as much as possible (e.g., font, colors, images, tests, margins) :point_down: 

Your Design:

![s2](https://user-images.githubusercontent.com/57562869/150556516-22e4b0c4-3aa4-4a42-9e33-a31d72122368.png)

Figma Design:

![s1](https://user-images.githubusercontent.com/57562869/150556583-3df014b9-8fae-4097-b41e-5794aff87a49.png)

2022-01-21 15:59 UTC, moise10r commented on index.html
> +                        </li>
- [ ] Please, Give the expected `width` to your `input` and `textarea` You need to make sure that your desktop version looks like the one in the Figma design template that you chose :point_down: 

Your Design:

![des1](https://user-images.githubusercontent.com/57562869/150557747-4396f244-3d15-4296-aa8c-7d12bc508280.png)


Figma Design:

![des2](https://user-images.githubusercontent.com/57562869/150557897-085556bf-6d7b-415c-96c7-cc7348917d69.png)

2022-01-21 15:59 UTC, moise10r commented on index.html
> +           </div>
- [ ] Your hamburger menu does not display correctly, kindly fix it :point_down: 

![hum](https://user-images.githubusercontent.com/57562869/150558910-43fc6f41-f177-4b51-be08-a79050989218.png)

2022-01-22 09:03 UTC, Rustamxon7 approved these changes
## Hi @telanet 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://i.pinimg.com/originals/77/0e/b0/770eb057449582c44672b2d2d1cc39b6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-01-22 09:03 UTC, Rustamxon7 commented on index.html
>      <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>
## GOOD JOB 👏
- [ ] [OPTIONAL] You made an awesome design `^_+`. I have a suggestion for you to help make it better. To your all buttons set `cursor: pointer;` on hover and it changes cursor something like this `👆`

2022-01-22 09:25 UTC, merged